
proxy:
  image: notjrbauer/react-analytics:latest
  command: nginx
  ports:
    - "80:80"
web:
  image: notjrbauer/analyticslibrary:latest
  command: node index.js
  ports:
    - "3000:3000"
  volumes:
    - .:/app
  links:
    - python-analytics
    - nodejs-analytics
    - ruby-analytics
python-analytics:
  image: notjrbauer/python-analytics:latest
  command: python index.py
  ports:
    - "4000:4000"
nodejs-analytics:
  image: notjrbauer/nodejs-analytics:latest
  command: node index.js
  ports:
    - "5000:5000"
ruby-analytics:
  image: notjrbauer/ruby-analytics:latest
  command: ruby index.rb
  ports:
    - "4002:4002"
